from typing import Any, TypedDict


CLAIM_STATUSES = {
    "supported",
    "partially_supported",
    "not_supported",
    "unverified",
}

TRACEABILITY_STATUSES = {
    "traceable",
    "untraceable",
}


class EvidenceReference(TypedDict):
    """
    Reference to a specific deterministic evidence item.

    The reference identifies:
    - the investigation that produced the evidence
    - the field being referenced
    - optionally, the entity/row being referenced
    """

    investigation: str
    field: str
    entity: str | None


class Claim(TypedDict):
    """
    Structured business claim produced by an investigation.

    The claim statement itself is generated by the reasoning
    layer, while evidence references must resolve against
    deterministic investigation evidence.
    """

    id: str
    statement: str
    status: str
    evidence_refs: list[EvidenceReference]
    traceability_status: str


def _is_valid_reference_shape(
    reference: Any,
) -> bool:
    """
    Validate the basic structure of an evidence reference.
    """

    if not isinstance(reference, dict):
        return False

    investigation = reference.get(
        "investigation"
    )

    field = reference.get(
        "field"
    )

    if "entity" not in reference:
        return False

    entity = reference["entity"]

    if not isinstance(
        investigation,
        str,
    ) or not investigation.strip():
        return False

    if not isinstance(
        field,
        str,
    ) or not field.strip():
        return False

    if (
        entity is not None
        and not isinstance(entity, str)
    ):
        return False

    return True


def _evidence_contains_field(
    evidence: Any,
    field: str,
) -> bool:
    """
    Determine whether the requested field exists
    in the supplied evidence.

    Evidence may be:
    - a dictionary
    - a list of dictionaries
    """

    if isinstance(evidence, dict):
        return field in evidence

    if isinstance(evidence, list):
        return any(
            isinstance(item, dict)
            and field in item
            for item in evidence
        )

    return False


def _evidence_contains_entity(
    evidence: Any,
    entity: str,
) -> bool:
    """
    Determine whether an entity exists in the supplied
    evidence.

    The current analytics evidence uses different entity
    fields depending on the investigation. For the first
    implementation, we inspect common identifying values
    rather than hard-coding individual analytics domains.
    """

    if isinstance(evidence, dict):
        return any(
            str(value) == entity
            for value in evidence.values()
        )

    if isinstance(evidence, list):
        for item in evidence:
            if not isinstance(item, dict):
                continue

            if any(
                str(value) == entity
                for value in item.values()
            ):
                return True

    return False


def validate_evidence_reference(
    reference: Any,
    evidence: dict[str, Any],
) -> bool:
    """
    Validate that an evidence reference resolves against
    deterministic investigation evidence.

    This function validates traceability only.

    It does NOT determine whether the evidence semantically
    supports the claim statement.
    """

    if not _is_valid_reference_shape(
        reference
    ):
        return False

    investigation = reference[
        "investigation"
    ]

    field = reference[
        "field"
    ]

    entity = reference.get(
        "entity"
    )

    if investigation not in evidence:
        return False

    investigation_evidence = evidence[
        investigation
    ]

    if not _evidence_contains_field(
        investigation_evidence,
        field,
    ):
        return False

    if entity is not None:
        if not _evidence_contains_entity(
            investigation_evidence,
            entity,
        ):
            return False

    return True


def validate_claim(
    claim: Any,
    evidence: dict[str, Any],
) -> Claim | None:
    """
    Validate and normalize a single claim.

    A claim is considered traceable only when every supplied
    evidence reference resolves against deterministic evidence.

    The semantic claim status is preserved when valid.
    However, traceability does not imply semantic support.
    """

    if not isinstance(
        claim,
        dict,
    ):
        return None

    claim_id = claim.get(
        "id"
    )

    statement = claim.get(
        "statement"
    )

    status = claim.get(
        "status",
        "unverified",
    )

    evidence_refs = claim.get(
        "evidence_refs",
        [],
    )

    if not isinstance(
        claim_id,
        str,
    ) or not claim_id.strip():
        return None

    if not isinstance(
        statement,
        str,
    ) or not statement.strip():
        return None

    if status not in CLAIM_STATUSES:
        status = "unverified"

    if not isinstance(
        evidence_refs,
        list,
    ):
        return None

    normalized_refs: list[
        EvidenceReference
    ] = []

    for reference in evidence_refs:
        if not validate_evidence_reference(
            reference,
            evidence,
        ):
            return None

        normalized_refs.append(
            {
                "investigation": reference[
                    "investigation"
                ],
                "field": reference[
                    "field"
                ],
                "entity": reference.get(
                    "entity"
                ),
            }
        )

    traceability_status = (
        "traceable"
        if normalized_refs
        else "untraceable"
    )

    return {
        "id": claim_id,
        "statement": statement,
        "status": status,
        "evidence_refs": normalized_refs,
        "traceability_status": traceability_status,
    }


def validate_claims(
    claims: Any,
    evidence: dict[str, Any],
) -> list[Claim]:
    """
    Validate a collection of claims against deterministic
    investigation evidence.

    Invalid claims are discarded rather than allowing
    unresolvable evidence references into the investigation
    result.
    """

    if not isinstance(
        claims,
        list,
    ):
        return []

    validated: list[Claim] = []

    for claim in claims:
        validated_claim = validate_claim(
            claim,
            evidence,
        )

        if validated_claim is not None:
            validated.append(
                validated_claim
            )

    return validated